#!/bin/sh

set -eu

PRISMA_BIN="${PRISMA_BIN:-/prisma-cli/node_modules/.bin/prisma}"
PRISMA_SCHEMA="${PRISMA_SCHEMA:-./apps/web/prisma/schema.prisma}"
BACKUP_RECEIPT="${USESEND_MIGRATION_BACKUP_RECEIPT:-/run/usesend-backup.receipt}"
MAX_BACKUP_AGE_SECONDS=86400
MAX_CLOCK_SKEW_SECONDS=300

usage() {
  cat <<'EOF'
Usage:
  sh /app/migrate.sh status
  USESEND_MIGRATION_BACKUP_REF=restic:<64-hex-snapshot-id> \
  USESEND_MIGRATION_BACKUP_RECEIPT=/run/usesend-backup.receipt \
  USESEND_MIGRATION_COMPATIBILITY=<backward-compatible|roll-forward-only> \
    sh /app/migrate.sh deploy

For deploy, mount the verification receipt generated by
postgres_restore_verify.sh read-only at /run/usesend-backup.receipt.
EOF
}

receipt_field() {
  key="$1"
  awk -F= -v key="$key" '
    $1 == key {
      sub(/^[^=]*=/, "")
      print
      exit
    }
  ' "$BACKUP_RECEIPT"
}

require_recent_epoch() {
  label="$1"
  value="$2"

  if ! printf '%s' "$value" | grep -Eq '^[0-9]+$'; then
    echo "Refusing migration: $label is missing or invalid in backup verification receipt." >&2
    exit 64
  fi

  now="$(date +%s)"
  age="$((now - value))"
  if [ "$age" -lt "-$MAX_CLOCK_SKEW_SECONDS" ]; then
    echo "Refusing migration: $label is unexpectedly in the future." >&2
    exit 64
  fi
  if [ "$age" -gt "$MAX_BACKUP_AGE_SECONDS" ]; then
    echo "Refusing migration: verified pre-migration backup is stale (>24 hours)." >&2
    exit 64
  fi
}

: "${DATABASE_URL:?DATABASE_URL must be set for Prisma migration operations}"

case "${1:-}" in
  status)
    exec "$PRISMA_BIN" migrate status --schema "$PRISMA_SCHEMA"
    ;;

  deploy)
    backup_ref="${USESEND_MIGRATION_BACKUP_REF:-}"
    compatibility="${USESEND_MIGRATION_COMPATIBILITY:-}"

    if [ -z "$backup_ref" ]; then
      echo "Refusing migration: USESEND_MIGRATION_BACKUP_REF must identify a verified pre-migration backup." >&2
      exit 64
    fi

    snapshot_id="${backup_ref#restic:}"
    if [ "$snapshot_id" = "$backup_ref" ] || ! printf '%s' "$snapshot_id" | grep -Eq '^[0-9a-f]{64}$'; then
      echo "Refusing migration: USESEND_MIGRATION_BACKUP_REF must be restic:<64-hex-snapshot-id>." >&2
      exit 64
    fi

    case "$compatibility" in
      backward-compatible|roll-forward-only)
        ;;
      *)
        echo "Refusing migration: USESEND_MIGRATION_COMPATIBILITY must be backward-compatible or roll-forward-only." >&2
        exit 64
        ;;
    esac

    if [ ! -r "$BACKUP_RECEIPT" ]; then
      echo "Refusing migration: verified backup receipt is not readable at $BACKUP_RECEIPT." >&2
      exit 64
    fi

    receipt_version="$(receipt_field receipt_version)"
    receipt_ref="$(receipt_field backup_ref)"
    receipt_kind="$(receipt_field backup_kind)"
    receipt_verification="$(receipt_field verification)"
    backup_created_at_epoch="$(receipt_field backup_created_at_epoch)"
    verified_at_epoch="$(receipt_field verified_at_epoch)"

    if [ "$receipt_version" != "1" ]; then
      echo "Refusing migration: unsupported or missing backup receipt version." >&2
      exit 64
    fi
    if [ "$receipt_ref" != "$backup_ref" ]; then
      echo "Refusing migration: backup receipt does not match USESEND_MIGRATION_BACKUP_REF." >&2
      exit 64
    fi
    if [ "$receipt_kind" != "pre-migration" ]; then
      echo "Refusing migration: backup receipt is not for a pre-migration backup." >&2
      exit 64
    fi
    if [ "$receipt_verification" != "passed" ]; then
      echo "Refusing migration: restore verification has not passed." >&2
      exit 64
    fi

    require_recent_epoch backup_created_at_epoch "$backup_created_at_epoch"
    require_recent_epoch verified_at_epoch "$verified_at_epoch"

    echo "Applying Prisma migrations after verified restore gate: $backup_ref"
    echo "Schema compatibility classification: $compatibility"
    exec "$PRISMA_BIN" migrate deploy --schema "$PRISMA_SCHEMA"
    ;;

  *)
    usage >&2
    exit 64
    ;;
esac
